name: Deploy to server

on: push

jobs:
    first_jobs:
        runs-on: ubuntu-latest

        steps:
            - name: "Hola mundo"
              run: echo "Hola mundo desde el primer job"
    second_job:
        if: ${{ github.ref == 'refs/heads/main' }}
        needs: first_jobs
        runs-on: ubuntu-latest

        steps:
            - name: "Hola mundo"
              run: echo "Hola mundo desde el segundo job 2"