name: Deploy to server

on: push

jobs:
    first_jobs:
        runs-on: ubuntu-latest
        steps:
              - name: Working dir
                id: step_1
                run: echo "my_variable= Hola mundo" >> $GITHUB_OUTPUT
              - name: Obtener mensaje
                run: echo "${{steps.step_1.outputs.my_variable}}"
    second_job:
        if: ${{ github.ref == 'refs/heads/main' }}
        needs: first_jobs
        runs-on: ubuntu-latest

        steps:
            - name: "Hola mundo"
              run: echo "Hola mundo desde el segundo job 2"